# Generated by Django 2.1.7 on 2019-02-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_winemag'),
    ]

    operations = [
        migrations.AddField(
            model_name='winemag',
            name='srno',
            field=models.IntegerField(null=True),
        ),
    ]
