# Generated by Django 2.1.7 on 2019-02-17 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190217_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winemag',
            name='points',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='winemag',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
