# Generated by Django 2.1.7 on 2019-02-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20190217_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winemag',
            name='price',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='winemag',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='winemag',
            name='region_1',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='winemag',
            name='region_2',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='winemag',
            name='variety',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
